### ISSUE TITLE
Can't start script with Intuos4 

### ISSUE THREAD

**Issue by matthieubruneau** [sanette/intuos4-oled#1]
Hi,
When I'm trying to start the script, I have an error saying this:
```
raise Exception ("ERROR: no corresponding directory found in %s for device (%04x,%04x)"%(DEVICES_PATH, vendor, product))
Exception: ERROR: no corresponding directory found in /sys/bus/hid/devices/ for device (056a,00b9)
```
Do you have any idea where it is coming from?
Here is what I get when listing the devices with xsetwacom:
Wacom Intuos4 6x9 stylus                id: 14  type: STYLUS    
Wacom Intuos4 6x9 eraser                id: 15  type: ERASER    
Wacom Intuos4 6x9 cursor                id: 16  type: CURSOR    
Wacom Intuos4 6x9 pad                   id: 17  type: PAD

I'm using centos7 with Linux 3.10.0-1062.12.1.el7.x86_64
Thanks for the help

**Comment by sanette** [comment]
I'm not familiar with Centos. What do you have in the /sys/bus/hid/devices/ directory?
(when the intuos is plugged in)
`ls /sys/bus/hid/devices/`

**Comment by matthieubruneau** [comment]
Thanks for the quick reply. Here is what I have:
0003:046D:C318.0001
0003:046D:C318.0002
0003:1B1C:1B2E.0003
0003:1B1C:1B2E.0004
Don't really what those are

**Comment by sanette** [comment]
weird, the intuos is not there. Make sure it is plugged in and tell me what you get with
`find /sys -name "*056A:00B9*"`

**Comment by matthieubruneau** [comment]
I checked it is plugged in, I can use the stylus and writing the command you just listed displays nothing

**Comment by sanette** [comment]
what about
`lsusb`
and
`modinfo hid-generic`

**Comment by sanette** [comment]
we can also try a global search (this may take several seconds ton complete):

`sudo find / -name wacom_led`

**Comment by matthieubruneau** [comment]
I decided to try with a virtual machine running ubuntu instead of Centos7, and it seems I don't have the issue with it. I guess centos 7 handles it differently. I will switch to ubuntu, as the specifics application which forced me to use centos 7 are not part anymore of my workflow. It will be much easier
